=== liuyuanyuannumberone/java-project/java-basic/src/web/D01_xml/bookshelf.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT books (book+)>          <!--books有且至少有一个book子元素-->
<!ELEMENT book (name,author,sale)>    <!--约束元素book的子元素为name,author,sale且必须按顺序-->
<!ELEMENT name (#PCDATA)>
<!ELEMENT author (#PCDATA)>
<!ELEMENT sale (#PCDATA)>

=== liuyuanyuannumberone/java-project/java-basic/src/web/D01_xml/books.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--<!DOCTYPE books SYSTEM "bookshelf.dtd">-->
<books xmlns="name"
       xmlns:xsi="http://www.w3.org/2001/XMLSchema‐instance"
       xsi:schemaLocation="name bookshelf.xsd">
    <book id="0001">
        <name id="11">JavaWeb开发教程</name>
        <author>张孝祥</author>
        <sale>100.00元</sale>
    </book>
    <book id="0002">
        <name id="12">三国演义</name>
        <author>罗贯中</author>
        <sale>100.00元</sale>
    </book>
</books>
